---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: custom-pipeline
spec:
  params:
    - name: git_ref
      type: string
    - name: git_ref_type
      type: string
    - name: repo_name
      type: string
    - name: repo_url
      type: string
  resources:
    - name: git-repo
      type: git
    - name: s2i-thoth
      type: image

  tasks:
    - name: odh-deployer
      taskRef:
        name: tag-build
      params:
        - name: git_ref
          value: $(params.git_ref)
        - name: repo_name
          value: $(params.repo_name)
        - name: registry
          value: "quay.io"
        - name: registry_org
          value: "modh"
        - name: registry_project
          value: odh-deployer
        - name: registry_secret
          value: "modh-pusher-secret"
        - name: context_path
          value: odh-deployer
        - name: dockerfile
          value: Dockerfile
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo

    - name: odh-operator-image
      taskRef:
        name: tag-build
      params:
        - name: git_ref
          value: $(params.git_ref)
        - name: repo_name
          value: $(params.repo_name)
        - name: registry
          value: "quay.io"
        - name: registry_org
          value: "modh"
        - name: registry_project
          value: odh-operator-image
        - name: registry_secret
          value: "modh-pusher-secret"
        - name: context_path
          value: odh-operator-image
        - name: dockerfile
          value: Dockerfile
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo
